### ISSUE TITLE
Json Tree Data Structure

### ISSUE THREAD

**Issue by frankleenDev** [sawood14012/Habibimart#1]
Hello,
Can I get a screen shot your data structure on the firebase database I keep getting runtime errors when I try to construct it.
blog->prod_id->desc
                       ->title
                      ........

**Comment by sawood14012** [comment]
hi @frankleenDev  
please find the screenshot attached and i am also attaching a built APK in case if that helps you..
thank you..
![datastruc](https://user-images.githubusercontent.com/18240985/55607205-33ab7c00-5799-11e9-99df-a108568f3956.png)

[app-debug.apk.zip](https://github.com/sawood14012/Habibimart/files/3046638/app-debug.apk.zip)

**Comment by sawood14012** [comment]
and share whatever the errors you get i would love to help you solve them
